steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-west1-docker.pkg.dev/weekly-stock-price-dashboard/scraper-images/fiverrr-scrape-abb',
      '.'
    ]

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/weekly-stock-price-dashboard/scraper-images/fiverrr-scrape-abb'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fiverrr-scrape-abb'
      - '--image'
      - 'europe-west1-docker.pkg.dev/weekly-stock-price-dashboard/scraper-images/fiverrr-scrape-abb'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '1024Mi'
      - '--timeout'
      - '300'
      - '--cpu'
      - '1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,ALLOW_SELF_RECALL=true'
      - '--port=8080'  # ✅ explicitly declare expected port (safe but optional)

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8  # ✅ ensures Chrome + Puppeteer builds are fast/stable
