steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'europe-west1-docker.pkg.dev/weekly-stock-price-dashboard/scraper-images/fiverrr-scrape-abb', 
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'europe-west1-docker.pkg.dev/weekly-stock-price-dashboard/scraper-images/fiverrr-scrape-abb'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fiverrr-scrape-abb'
      - '--image'
      - 'europe-west1-docker.pkg.dev/weekly-stock-price-dashboard/scraper-images/fiverrr-scrape-abb'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,ALLOW_SELF_RECALL=true'

options:
  logging: CLOUD_LOGGING_ONLY
